config/routes.rb
Rails.application.routes.draw do
  root to: 'tasks#index'
  namespace :admin do
    resources :users
  end
  resources :tasks, except: :show do
    member do
      patch :update_state
    end
  end
  namespace :guest do
    post '/login', to: 'sessions#create'
  end
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '*not_found' => 'application#routing_error'
  post '*not_found' => 'application#routing_error'
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token

  has_many :tasks, dependent: :destroy
  before_save { self.email = email.downcase }
  before_destroy :must_not_destroy_last_admin
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: true
  validates :password, presence: true, length: { minimum: 8 }

  has_secure_password

  scope :recent, -> { order(created_at: :desc) }

  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def self.find_or_create_guest_user
    find_or_create_by(email: 'guest@example.com') do |user|
      user.name = 'guest'
      user.password = 'password'
      user.admin = false
    end
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
    remember_digest
  end

  def session_token
    remember_digest || remember
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?

    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  private

  def must_not_destroy_last_admin
    if admin? && User.where(admin: true).count == 1
      errors.add(:base, '管理者ユーザーは最低一人必要です')
      throw(:abort)
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  skip_before_action :set_search_form
  before_action :require_admin
  before_action :set_user, only: %i[show edit update destroy]

  def index
    @users = User.preload(:tasks).recent
  end

  def show
    @tasks = @user.tasks.recent.page(params[:page])
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash.now[:success] = "ユーザー: #{@user.name}を登録しました"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @user.update(user_params)
      flash.now[:success] = "ユーザー: #{@user.name}を更新しました"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @user.destroy
      if request.referer.match? %r{/admin/users/\d+}
        flash[:success] = "ユーザー: #{@user.name}を削除しました"
        redirect_to admin_users_path
      else
        flash.now[:success] = "ユーザー: #{@user.name}を削除しました"
      end
    else
      flash.now[:danger] = @user.errors.full_messages[0]
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_admin
    routing_error unless current_user.admin?
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_form.html.slim
= turbo_frame_tag user
  - if user.errors.present?
    ul#error_explanation
      - user.errors.full_messages.each do |message|
        li = message

  = form_with model: [:admin, user], data: { action: 'turbo:submit-end->modal#close' } do |f|
    .form-group.mb-3
      = f.label :name
      = f.text_field :name, class: 'form-control'
    .form-group.mb-3
      = f.label :email
      = f.email_field :email, class: 'form-control'
    .form-group.mb-3
      = f.label :password
      = f.password_field :password, class: 'form-control'
    .form-group.mb-3
      = f.label :password_confirmation
      = f.password_field :password_confirmation, class: 'form-control'
    .form-check.mb-3
      = f.label :admin, class: 'form-check-label' do
        = f.check_box :admin, class: 'form-check-input'
        | 管理者権限
    = f.submit nil, class: 'btn btn-primary'

app/views/admin/users/_sidebar.html.slim
.d-flex.flex-column.flex-shrink-0.py-3.ps-4.pe-3.bg-primary.vh-100
  .d-flex.align-items-center.justify-content-center
    = link_to 'TaskManager', admin_users_path, class: "fs-3 text-decoration-none link-light fw-bold"
  span.text-primary.text-center.bg-light.fw-bold Admin
  hr

  .mb-4.text-center
    = link_to 'ユーザーを登録する', new_admin_user_path, class: 'text-decoration-none link-light', data: { turbo_frame: 'modal' }

app/views/admin/users/_task.html.slim
.row.py.border-top.accordion id="accordion-#{task.id}"
  .col-3.my-auto
    button.btn.btn-link type="button" data-test="task-title" data-bs-toggle="collapse" data-bs-target="#detail-#{task.id}" = task.title
  .col-1.my-auto.text-center
    = state_budge(task)
  .col-4.my-auto.pt-2
    - task.tags.each do |tag|
      span.badge.me-1.mb-2.text-bg-secondary.fs-6 = tag.name
  .col-2.my-auto.text-center.text-black-50
    = l(task.deadline, format: :long)
  .col-1.my-auto.text-center
    = priority_badge(task)
  .col-1.my-auto.px-1
  .collapse id="detail-#{task.id}" data-bs-parent="#accordion-#{task.id}"
    p.text-black-50 = '説明 : ' + task.description
    p.text-black-50 = '作成日 : ' + l(task.created_at, format: :long)
    p.text-black-50 = '更新日 : ' + l(task.updated_at, format: :long)

app/views/admin/users/_user.html.slim
= turbo_frame_tag user
  .col
    .card.my-3.mx-auto
      .card-header.bg-primary
        .d-flex.justify-content-between
          h5.card-title.my-auto = link_to user.name, [:admin, user], data: { test: 'user-title', turbo: false }, class: "text-decoration-none link-light"
          - if user.admin?
            span.badge.rounded-pill.my-auto.text-bg-light
              | 管理者
      .card-body
        span data-test="task-count" = "タスク数: #{user.tasks.length}"
        .d-flex.justify-content-between
          = "登録日: #{l(user.created_at, format: :long)}"
          div
            = link_to '編集', edit_admin_user_path(user), class: 'mx-1 text-decoration-none', data: { turbo_frame: 'modal' }
            = link_to '削除', [:admin, user], data: { turbo_method: :delete, turbo_confirm: '本当に削除しますか？' }, class: 'mx-1 text-decoration-none'

app/views/admin/users/create.turbo_stream.slim
= turbo_stream.prepend 'user-list', @user
= turbo_stream.update 'flash', partial: 'flash'

app/views/admin/users/destroy.turbo_stream.slim
= turbo_stream.remove @user
= turbo_stream.update 'flash', partial: 'flash'

app/views/admin/users/edit.html.slim
= render 'modal', title: '編集'
  = render 'form', user: @user

app/views/admin/users/index.html.slim
.row.row-cols-3 data-test="user-list" id="user-list"
  - @users.each do |user|
    = render partial: 'user', locals: { user: user }

app/views/admin/users/new.html.slim
= render 'modal', title: '新規作成'
  = render 'form', user: @user

app/views/admin/users/show.html.slim
= turbo_frame_tag @user
  table.table
    tbody
      tr
        th 名前
        td id="user-name" = @user.name
      tr
        th email
        td id="user-email" = simple_format(h(@user.email), { class: 'mb-0' }, sanitaize: false )
      tr
        th ロール
        td id="user-role" = @user.admin? ? '管理者' : '一般'
      tr
        th 登録日時
        td = l(@user.created_at, format: :long)
      tr
        th 更新日時
        td id="user-updated-at" = l(@user.updated_at, format: :long)
= link_to '編集', edit_admin_user_path(@user), class: 'btn btn-primary mx-1', data: { turbo_frame: 'modal' }
= link_to '削除', [:admin, @user], data: { turbo_method: :delete, turbo_confirm: '本当に削除しますか？' }, class: 'btn btn-primary mx-1'
.card.shadow.mt-3
  .card-header.text-black-50 タスク一覧
  .card-body.mx-3
    .row
      .col-3.pb-2.text-center
        span.bi-pencil.text-black-50
      .col-1.pb-2.text-center
        span.bi-check2-circle.text-black-50
      .col-4.pb-2.text-center
        span.bi-tag.text-black-50
      .col-2.pb-2.text-center
        span.bi-hourglass-split.text-black-50
      .col-1.pb-2.text-center
        span.bi-exclamation-circle.text-black-50
    div id="task-list"
    - @tasks.each do |task|
      = render partial: 'task', locals: { task: task }
  .d-flex.justify-content-end.my-4.me-3
    = paginate @tasks

app/views/admin/users/update.turbo_stream.slim
- if request.referer.match? /admin\/users\/\d+/
  = turbo_stream.update "user-name", @user.name
  = turbo_stream.update "user-email", @user.email
  = turbo_stream.update "user-role", @user.admin ? '管理者' : '一般'
  = turbo_stream.update "user-updated-at", l(@user.updated_at, format: :long)
- else
  = turbo_stream.replace @user
= turbo_stream.update 'flash', partial: 'flash'