config/routes.rb
Rails.application.routes.draw do
  root to: 'tasks#index'
  namespace :admin do
    resources :users
  end
  resources :tasks, except: :show do
    member do
      patch :update_state
    end
  end
  namespace :guest do
    post '/login', to: 'sessions#create'
  end
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '*not_found' => 'application#routing_error'
  post '*not_found' => 'application#routing_error'
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | TaskManager
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    meta[name="turbo-cache-control" content="no-cache"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_include_tag "application", "data-turbo-track": "reload", defer: true
  body
    .vh-100
      .caotainer-fluid
        .row
          .px-0(style="width: 250px")
          .px-0.position-fixed(style="width: 250px")
            = render partial: 'application/sidebar', locals: { search_form: @search_form }
          .col.ps-0.pe-4
            .d-flex.justify-content-end.py-2.my-2
              - if current_user.admin?
                = link_to 'ユーザー管理へ', admin_users_path, class: 'text-decoration-none mx-2'
              = link_to 'ログアウト', logout_path, data: { turbo_method: :delete }, class: 'text-decoration-none mx-2'
            .col.mb-4.ms-4
              div id="flash"
                = render 'flash'
              = yield
    = turbo_frame_tag 'modal'

app/views/layouts/errors.html.slim
doctype html
html
  head
    title
      | TaskManage
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_include_tag "application", "data-turbo-track": "reload", defer: true
  body
    = yield

app/views/layouts/sessions.html.slim
doctype html
html
  head
    title
      | TaskManager
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_include_tag "application", "data-turbo-track": "reload", defer: true
  body.bg-light
    - if flash.any?
      - flash.each do |message_type, message|
        .col.my-4.mx-4
          = content_tag(:div, message, class: "alert alert-#{message_type}")
    .d-flex.align-items-center.my-5
      = yield